"""ATT&CK Navigator layer export — M22 Phase 6/7.

Produces a Navigator-compatible JSON layer from fused techniques and
optional attack-path technique coverage. Hardening P2: hard size cap.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from redforge.domain.threat_intel.fusion_value_objects import (
    FusedIndicatorType,
    IndicatorLifecycle,
)
from redforge.infrastructure.database.repositories.attack_path_repository import (
    SqlAlchemyAttackPathRepository,
)
from redforge.infrastructure.database.repositories.threat_fusion_repository import (
    SqlAlchemyFusedIndicatorRepository,
)

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

MAX_TECHNIQUES_IN_LAYER = 400


@dataclass(frozen=True, slots=True)
class NavigatorLayer:
    name: str
    domain: str
    versions: dict[str, str]
    techniques: list[dict[str, Any]]
    truncated: bool


class AttackNavigatorExportService:
    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._session_factory = session_factory

    async def export_layer(
        self,
        *,
        organization_id: str,
        name: str = "RedForge Threat Intelligence",
        investigation_id: str | None = None,
    ) -> NavigatorLayer:
        technique_scores: dict[str, float] = {}
        async with self._session_factory() as session, session.begin():
            fused_repo = SqlAlchemyFusedIndicatorRepository(session)
            techniques = await fused_repo.list_by_type(
                FusedIndicatorType.TECHNIQUE,
                lifecycle=IndicatorLifecycle.ACTIVE,
                limit=MAX_TECHNIQUES_IN_LAYER + 1,
                offset=0,
            )
            for item in techniques[:MAX_TECHNIQUES_IN_LAYER]:
                # canonical_key shape: technique:<id>
                tech_id = item.canonical_key.value.split(":", 1)[-1].upper()
                score = 1.0
                if item.confidence is not None:
                    rank = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "VERY_HIGH": 4}.get(
                        item.confidence.value, 1
                    )
                    score = float(rank)
                technique_scores[tech_id] = max(technique_scores.get(tech_id, 0.0), score)

            if investigation_id:
                path_repo = SqlAlchemyAttackPathRepository(session)
                paths = await path_repo.list_for_investigation(
                    organization_id, investigation_id, limit=20
                )
                for path in paths:
                    for tech_id in path.technique_coverage:
                        key = tech_id.upper()
                        technique_scores[key] = max(
                            technique_scores.get(key, 0.0), 4.0
                        )

        truncated = len(techniques) > MAX_TECHNIQUES_IN_LAYER
        tech_list = [
            {
                "techniqueID": tid,
                "score": score,
                "color": "",
                "comment": "",
                "enabled": True,
                "metadata": [],
                "links": [],
                "showSubtechniques": False,
            }
            for tid, score in sorted(technique_scores.items())[:MAX_TECHNIQUES_IN_LAYER]
        ]
        return NavigatorLayer(
            name=name[:128],
            domain="enterprise-attack",
            versions={"attack": "14", "navigator": "4.9", "layer": "4.5"},
            techniques=tech_list,
            truncated=truncated,
        )

    def to_navigator_json(self, layer: NavigatorLayer) -> dict[str, Any]:
        return {
            "name": layer.name,
            "versions": layer.versions,
            "domain": layer.domain,
            "description": (
                "Generated by AIVAR RedForge from fused ATT&CK techniques"
                + (" (truncated)" if layer.truncated else "")
            ),
            "filters": {
                "platforms": [
                    "Windows",
                    "Linux",
                    "macOS",
                    "Network",
                    "PRE",
                    "Containers",
                    "Office 365",
                    "SaaS",
                    "Google Workspace",
                    "IaaS",
                    "Identity Provider",
                ]
            },
            "sorting": 0,
            "layout": {
                "layout": "side",
                "aggregateFunction": "average",
                "showID": False,
                "showName": True,
                "showAggregateScores": False,
                "countUnscored": False,
            },
            "hideDisabled": False,
            "techniques": layer.techniques,
            "gradient": {
                "colors": ["#ffffff", "#66b1ff", "#ff6666"],
                "minValue": 0,
                "maxValue": 4,
            },
            "legendItems": [],
            "metadata": [],
            "links": [],
            "showTacticRowBackground": False,
            "tacticRowBackground": "#dddddd",
            "selectTechniquesAcrossTactics": True,
            "selectSubtechniquesWithParent": False,
        }
