"""Audit and vault backend enums."""

from __future__ import annotations

from enum import StrEnum


class AuditOperation(StrEnum):
    CREATED = "CREATED"
    ACTIVATED = "ACTIVATED"
    VERSION_ADDED = "VERSION_ADDED"
    ROTATION_STARTED = "ROTATION_STARTED"
    ROTATION_COMMITTED = "ROTATION_COMMITTED"
    ROTATION_ABORTED = "ROTATION_ABORTED"
    DISABLED = "DISABLED"
    ENABLED = "ENABLED"
    REVOKED = "REVOKED"
    EMERGENCY_REVOKED = "EMERGENCY_REVOKED"
    EXPIRED = "EXPIRED"
    RECOVERED = "RECOVERED"
    RENEWED = "RENEWED"
    DELETED = "DELETED"
    ACCESSED = "ACCESSED"
    BREAK_GLASS = "BREAK_GLASS"
    EMERGENCY_OVERRIDE = "EMERGENCY_OVERRIDE"
    METADATA_UPDATED = "METADATA_UPDATED"
    VERSION_ROLLED_BACK = "VERSION_ROLLED_BACK"
    POLICY_ATTACHED = "POLICY_ATTACHED"
    POLICY_DETACHED = "POLICY_DETACHED"


class AuditOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    DENIED = "DENIED"
    FAILURE = "FAILURE"


class VaultBackendType(StrEnum):
    AWS_SECRETS_MANAGER = "AWS_SECRETS_MANAGER"
    HASHICORP_VAULT = "HASHICORP_VAULT"
    AZURE_KEY_VAULT = "AZURE_KEY_VAULT"
    GCP_SECRET_MANAGER = "GCP_SECRET_MANAGER"
    LOCAL_ENCRYPTED = "LOCAL_ENCRYPTED"


class RotationTrigger(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"
    POLICY = "POLICY"
    BREAK_GLASS = "BREAK_GLASS"
