"""Findings REST API endpoints."""

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, Field

from redforge.api.dependencies import get_finding_service
from redforge.api.security import TenantContext, require_permission
from redforge.application.findings import FindingDTO, FindingService
from redforge.domain.identity.value_objects import Permission

router = APIRouter(prefix="/findings", tags=["findings"])


# ─── Request/Response Models ──────────────────────────────────────────────────


class CreateFindingRequest(BaseModel):
    """organization_id is intentionally NOT a field — derived from the
    caller's verified TenantContext."""

    run_id: str
    target_id: str
    evidence_ids: list[str] = Field(..., min_length=1)
    title: str = Field(..., min_length=5, max_length=300)
    description: str = ""
    severity: str = Field(..., pattern=r"^(critical|high|medium|low|informational)$")
    risk_score: float = Field(..., ge=0.0, le=10.0)
    recommendation: str = ""


class FindingResponse(BaseModel):
    id: str
    organization_id: str
    run_id: str
    target_id: str
    evidence_ids: list[str]
    title: str
    description: str
    severity: str
    risk_score: float
    status: str
    recommendation: str
    created_at: str
    updated_at: str

    @classmethod
    def from_dto(cls, dto: FindingDTO) -> "FindingResponse":
        return cls(
            id=dto.id, organization_id=dto.organization_id,
            run_id=dto.run_id, target_id=dto.target_id,
            evidence_ids=dto.evidence_ids, title=dto.title,
            description=dto.description, severity=dto.severity,
            risk_score=dto.risk_score, status=dto.status,
            recommendation=dto.recommendation,
            created_at=dto.created_at, updated_at=dto.updated_at,
        )


class CloseFindingRequest(BaseModel):
    reason: str = Field(default="resolved")


# ─── Endpoints ────────────────────────────────────────────────────────────────
#
# Permission note: the RBAC model has no dedicated "findings:write"
# permission (findings are normally system-generated by ValidationService,
# not manually authored) — write operations here use VALIDATIONS_MANAGE,
# the closest existing permission for mutating security assessment data.


@router.post("", response_model=FindingResponse, status_code=201)
async def create_finding(
    body: CreateFindingRequest,
    tenant: TenantContext = Depends(require_permission(Permission.VALIDATIONS_MANAGE)),
    service: FindingService = Depends(get_finding_service),
) -> FindingResponse:
    """Create a new finding from evidence."""
    dto = await service.create(
        organization_id=tenant.organization_id, run_id=body.run_id,
        target_id=body.target_id, evidence_ids=body.evidence_ids,
        title=body.title, description=body.description,
        severity=body.severity, risk_score=body.risk_score,
        recommendation=body.recommendation,
    )
    return FindingResponse.from_dto(dto)


@router.get("/{finding_id}", response_model=FindingResponse)
async def get_finding(
    finding_id: str,
    tenant: TenantContext = Depends(require_permission(Permission.FINDINGS_READ)),
    service: FindingService = Depends(get_finding_service),
) -> FindingResponse:
    """Retrieve a finding by ID, scoped to the caller's organization."""
    dto = await service.get_by_id(finding_id, tenant.organization_id)
    return FindingResponse.from_dto(dto)


@router.get("", response_model=list[FindingResponse])
async def list_findings(
    target_id: str | None = Query(default=None),
    severity: str | None = Query(default=None),
    status: str | None = Query(default=None),
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
    tenant: TenantContext = Depends(require_permission(Permission.FINDINGS_READ)),
    service: FindingService = Depends(get_finding_service),
) -> list[FindingResponse]:
    """List findings for the caller's organization."""
    dtos = await service.list_findings(
        tenant.organization_id, target_id, severity, status, limit, offset,
    )
    return [FindingResponse.from_dto(d) for d in dtos]


@router.post("/{finding_id}/close", response_model=FindingResponse)
async def close_finding(
    finding_id: str,
    body: CloseFindingRequest,
    tenant: TenantContext = Depends(require_permission(Permission.VALIDATIONS_MANAGE)),
    service: FindingService = Depends(get_finding_service),
) -> FindingResponse:
    """Close a finding, scoped to the caller's organization."""
    dto = await service.close(finding_id, tenant.organization_id)
    return FindingResponse.from_dto(dto)


@router.post("/{finding_id}/reopen", response_model=FindingResponse)
async def reopen_finding(
    finding_id: str,
    tenant: TenantContext = Depends(require_permission(Permission.VALIDATIONS_MANAGE)),
    service: FindingService = Depends(get_finding_service),
) -> FindingResponse:
    """Reopen a previously closed finding, scoped to the caller's organization."""
    dto = await service.reopen(finding_id, tenant.organization_id)
    return FindingResponse.from_dto(dto)
