"""Credential Vault domain events."""

from credential_vault.domain.events.backend_events import (
    VaultBackendDeleted,
    VaultBackendRegistered,
)
from credential_vault.domain.events.base import BaseDomainEvent
from credential_vault.domain.events.credential_events import (
    BreakGlassAccessed,
    BulkRevocationInitiated,
    CredentialAccessed,
    CredentialCreated,
    CredentialDeleted,
    CredentialDisabled,
    CredentialEnabled,
    CredentialExpirationWarning,
    CredentialExpired,
    CredentialMetadataUpdated,
    CredentialRecovered,
    CredentialRenewed,
    CredentialRevoked,
    CredentialRotated,
    CredentialRotationStarted,
    CredentialVersionCreated,
    EmergencyOverrideAccessed,
    EmergencyRevoked,
    ExpirationPolicyAttached,
    ExpirationPolicyDetached,
    RotationAborted,
    RotationPolicyAttached,
    RotationPolicyDetached,
    VersionRolledBack,
)
from credential_vault.domain.events.policy_events import (
    ExpirationPolicyCreated,
    ExpirationPolicyDeleted,
    ExpirationPolicyUpdated,
    RotationPolicyCreated,
    RotationPolicyDeleted,
    RotationPolicyUpdated,
)

__all__ = [
    "BaseDomainEvent",
    "BreakGlassAccessed",
    "BulkRevocationInitiated",
    "CredentialAccessed",
    "CredentialCreated",
    "CredentialDeleted",
    "CredentialDisabled",
    "CredentialEnabled",
    "CredentialExpirationWarning",
    "CredentialExpired",
    "CredentialMetadataUpdated",
    "CredentialRecovered",
    "CredentialRenewed",
    "CredentialRevoked",
    "CredentialRotated",
    "CredentialRotationStarted",
    "CredentialVersionCreated",
    "EmergencyOverrideAccessed",
    "EmergencyRevoked",
    "ExpirationPolicyAttached",
    "ExpirationPolicyCreated",
    "ExpirationPolicyDeleted",
    "ExpirationPolicyDetached",
    "ExpirationPolicyUpdated",
    "RotationAborted",
    "RotationPolicyAttached",
    "RotationPolicyCreated",
    "RotationPolicyDeleted",
    "RotationPolicyDetached",
    "RotationPolicyUpdated",
    "VaultBackendDeleted",
    "VaultBackendRegistered",
    "VersionRolledBack",
]
