"""Domain events for the AI Security Intelligence bounded context."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime


def _now() -> datetime:
    return datetime.now(UTC)


@dataclass(frozen=True, slots=True)
class IntelligenceDomainEvent:
    """Base for all intelligence domain events."""

    event_id: str
    occurred_at: datetime = field(default_factory=_now)


@dataclass(frozen=True, slots=True)
class InsightDetected(IntelligenceDomainEvent):
    """A SecurityInsight was detected from evidence/risk signals."""

    insight_id: str = ""
    organization_id: str = ""
    insight_type: str = ""
    title: str = ""
    affected_target_count: int = 0


@dataclass(frozen=True, slots=True)
class RecommendationGenerated(IntelligenceDomainEvent):
    """A Recommendation was generated by a rule."""

    recommendation_id: str = ""
    organization_id: str = ""
    target_id: str = ""
    category: str = ""
    priority: str = ""
    rule_id: str = ""


@dataclass(frozen=True, slots=True)
class CoverageGapIdentified(IntelligenceDomainEvent):
    """An attack coverage gap was identified for a target."""

    organization_id: str = ""
    target_id: str = ""
    missing_category_count: int = 0
    coverage_rate: float = 0.0


@dataclass(frozen=True, slots=True)
class IntelligenceReportCreated(IntelligenceDomainEvent):
    """An IntelligenceReport was assembled for an organization."""

    report_id: str = ""
    organization_id: str = ""
    recommendation_count: int = 0
    insight_count: int = 0
    critical_recommendation_count: int = 0
