"""Credential Vault domain exceptions."""

from credential_vault.domain.exceptions.domain_exceptions import (
    AccessDenied,
    ActiveVersionNotFound,
    BreakGlassJustificationRequired,
    ConcurrentRotationConflict,
    CredentialAlreadyExists,
    CredentialIsDeleted,
    CredentialIsExpired,
    CredentialIsRevoked,
    CredentialNotFound,
    DomainException,
    DuplicatePolicyName,
    InsufficientApprovers,
    InvalidArgument,
    InvalidStateTransition,
    NoPolicyAttached,
    OptimisticLockConflict,
    PolicyInUse,
    PolicyNotFound,
    RecoveryVersionInvalid,
    ResolvedSecretZeroized,
    TenantMismatch,
    VaultBackendInUse,
    VaultBackendNotFound,
    VersionNotFound,
)

__all__ = [
    "AccessDenied",
    "ActiveVersionNotFound",
    "BreakGlassJustificationRequired",
    "ConcurrentRotationConflict",
    "CredentialAlreadyExists",
    "CredentialIsDeleted",
    "CredentialIsExpired",
    "CredentialIsRevoked",
    "CredentialNotFound",
    "DomainException",
    "DuplicatePolicyName",
    "InsufficientApprovers",
    "InvalidArgument",
    "InvalidStateTransition",
    "NoPolicyAttached",
    "OptimisticLockConflict",
    "PolicyInUse",
    "PolicyNotFound",
    "RecoveryVersionInvalid",
    "ResolvedSecretZeroized",
    "TenantMismatch",
    "VaultBackendInUse",
    "VaultBackendNotFound",
    "VersionNotFound",
]
