"use client";

import { useState } from "react";
import {
  AsyncContent,
  DataConsole,
  FormField,
  FormModal,
  InvestigationDrawer,
  KpiTile,
  PageHeader,
  Panel,
  StatusPill,
  useAsync,
  fmtTime,
  type ConsoleColumn,
  type DrawerField,
} from "@/components/cc";
import {
  listTemplates,
  listReportInstances,
  generateReportOnDemand,
  createScheduledReport,
  downloadExportedReport,
  listDeliveryAudit,
  type ReportInstanceDTO,
  type ReportTemplate,
} from "@/lib/reporting";
import { getMe } from "@/lib/auth";

const EXPORT_FORMATS = ["CSV", "JSON", "PDF"];

export default function ReportingPage() {
  const templates = useAsync(() => listTemplates(), []);
  const instances = useAsync(() => listReportInstances(), []);
  const audit = useAsync(() => listDeliveryAudit(), []);
  const [tab, setTab] = useState<"instances" | "templates" | "audit">("instances");
  const [selected, setSelected] = useState<ReportInstanceDTO | null>(null);
  const [showGenerate, setShowGenerate] = useState(false);
  const [showSchedule, setShowSchedule] = useState(false);
  const [busy, setBusy] = useState(false);

  return (
    <>
      <PageHeader
        title="Reporting"
        subtitle="On-demand and scheduled report generation, export, and delivery audit"
        actions={
          <div className="flex gap-2">
            <button
              onClick={() => setShowSchedule(true)}
              className="rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300 hover:border-red-800 hover:text-red-300"
            >
              Schedule Report
            </button>
            <button
              onClick={() => setShowGenerate(true)}
              className="rounded-md border border-red-800 bg-red-950/50 px-3 py-1.5 text-xs text-red-300 hover:bg-red-900/50"
            >
              Generate Report
            </button>
          </div>
        }
      />

      <div className="mb-4 flex gap-1 rounded-lg border border-gray-800 bg-gray-900 p-1">
        {(["instances", "templates", "audit"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`rounded-md px-4 py-1.5 text-xs font-medium capitalize ${
              tab === t ? "bg-red-950/60 text-red-300" : "text-gray-400 hover:text-gray-200"
            }`}
          >
            {t === "instances" ? "Reports" : t === "templates" ? "Templates" : "Delivery Audit"}
          </button>
        ))}
      </div>

      {tab === "instances" && (
        <InstancesTab state={instances} onSelect={setSelected} onDownload={downloadExportedReport} />
      )}
      {tab === "templates" && <TemplatesTab state={templates} />}
      {tab === "audit" && <AuditTab state={audit} />}

      {selected && (
        <InvestigationDrawer
          open
          title={selected.report_type.replace(/_/g, " ")}
          subtitle={selected.instance_id}
          onClose={() => setSelected(null)}
          fields={instanceFields(selected)}
        />
      )}

      {showGenerate && (
        <GenerateModal
          templates={templates.data || []}
          onClose={() => setShowGenerate(false)}
          onGenerated={() => {
            instances.reload();
            setShowGenerate(false);
          }}
        />
      )}

      {showSchedule && (
        <ScheduleModal
          templates={templates.data || []}
          onClose={() => setShowSchedule(false)}
          onCreated={() => setShowSchedule(false)}
        />
      )}
    </>
  );
}

function instanceFields(r: ReportInstanceDTO): DrawerField[] {
  return [
    { label: "Status", value: <StatusPill status={r.status} /> },
    { label: "Report Type", value: r.report_type },
    { label: "Trigger", value: r.trigger },
    { label: "Generated By", value: r.generated_by },
    { label: "Created At", value: fmtTime(r.created_at) },
    { label: "Completed At", value: r.completed_at ? fmtTime(r.completed_at) : "Not completed" },
    ...(r.error_reason ? [{ label: "Error", value: <span role="alert" className="text-red-400">{r.error_reason}</span> }] : []),
    { label: "Narrative", value: <span className="whitespace-pre-wrap text-xs">{r.narrative}</span> },
  ];
}

function InstancesTab({
  state,
  onSelect,
  onDownload,
}: {
  state: ReturnType<typeof useAsync<ReportInstanceDTO[]>>;
  onSelect: (r: ReportInstanceDTO) => void;
  onDownload: (instanceId: string, format: string) => void;
}) {
  const cols: ConsoleColumn<ReportInstanceDTO>[] = [
    { key: "type", header: "Type", width: "18%", render: (r) => <span className="text-gray-200">{r.report_type.replace(/_/g, " ")}</span> },
    { key: "status", header: "Status", width: "12%", render: (r) => <StatusPill status={r.status} /> },
    { key: "trigger", header: "Trigger", width: "12%", render: (r) => r.trigger },
    { key: "generated_by", header: "Generated By", width: "16%", render: (r) => r.generated_by },
    { key: "created_at", header: "Created At", width: "16%", render: (r) => fmtTime(r.created_at) },
    {
      key: "actions",
      header: "Export",
      width: "26%",
      render: (r) => (
        <div className="flex gap-1.5" onClick={(e) => e.stopPropagation()}>
          {EXPORT_FORMATS.map((f) => (
            <button
              key={f}
              onClick={() => onDownload(r.instance_id, f)}
              disabled={r.status !== "COMPLETED" && r.status !== "completed"}
              className="rounded border border-gray-700 px-1.5 py-0.5 text-[10px] text-gray-300 hover:border-red-800 hover:text-red-300 disabled:opacity-40"
            >
              {f}
            </button>
          ))}
        </div>
      ),
    },
  ];
  return (
    <>
      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
        <AsyncContent state={state}>
          {(list) => <KpiTile label="Total Reports" value={list.length} />}
        </AsyncContent>
        <AsyncContent state={state}>
          {(list) => (
            <KpiTile
              label="Completed"
              value={list.filter((r) => r.status.toUpperCase() === "COMPLETED").length}
              tone="ok"
            />
          )}
        </AsyncContent>
        <AsyncContent state={state}>
          {(list) => (
            <KpiTile
              label="Failed"
              value={list.filter((r) => r.status.toUpperCase() === "FAILED").length}
              tone="danger"
            />
          )}
        </AsyncContent>
        <AsyncContent state={state}>
          {(list) => (
            <KpiTile
              label="Pending"
              value={list.filter((r) => r.status.toUpperCase() === "PENDING" || r.status.toUpperCase() === "RUNNING").length}
              tone="warning"
            />
          )}
        </AsyncContent>
      </div>
      <AsyncContent state={state} empty={(d) => d.length === 0} emptyLabel="No reports generated yet.">
        {(list) => (
          <DataConsole columns={cols} rows={list} rowKey={(r) => r.instance_id} onRowClick={onSelect} emptyLabel="No reports generated yet." />
        )}
      </AsyncContent>
    </>
  );
}

function TemplatesTab({ state }: { state: ReturnType<typeof useAsync<ReportTemplate[]>> }) {
  const cols: ConsoleColumn<ReportTemplate>[] = [
    { key: "name", header: "Template", width: "26%", render: (r) => <span className="text-gray-200">{r.name}</span> },
    { key: "type", header: "Report Type", width: "20%", render: (r) => r.report_type },
    { key: "sections", header: "Sections", width: "40%", render: (r) => r.sections.join(", ") || "—" },
    { key: "id", header: "ID", width: "14%", render: (r) => <span className="font-mono text-[10px] text-gray-600">{r.template_id.slice(0, 10)}…</span> },
  ];
  return (
    <AsyncContent state={state} empty={(d) => d.length === 0} emptyLabel="No report templates configured.">
      {(list) => <DataConsole columns={cols} rows={list} rowKey={(r) => r.template_id} emptyLabel="No report templates configured." />}
    </AsyncContent>
  );
}

function AuditTab({ state }: { state: ReturnType<typeof useAsync<Array<Record<string, unknown>>>> }) {
  return (
    <AsyncContent state={state} empty={(d) => d.length === 0} emptyLabel="No delivery audit entries recorded.">
      {(list) => (
        <Panel title="Delivery Audit Trail">
          <div className="divide-y divide-gray-800">
            {list.map((entry, i) => (
              <div key={i} className="px-4 py-3">
                <pre className="whitespace-pre-wrap text-[11px] text-gray-400">{JSON.stringify(entry, null, 2)}</pre>
              </div>
            ))}
          </div>
        </Panel>
      )}
    </AsyncContent>
  );
}

function GenerateModal({
  templates,
  onClose,
  onGenerated,
}: {
  templates: ReportTemplate[];
  onClose: () => void;
  onGenerated: () => void;
}) {
  const [templateId, setTemplateId] = useState(templates[0]?.template_id || "");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit() {
    if (!templateId) {
      setError("Select a template.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const me = await getMe().catch(() => null);
      await generateReportOnDemand({ template_id: templateId, generated_by: me?.email || "console" });
      onGenerated();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate report");
    } finally {
      setBusy(false);
    }
  }

  return (
    <FormModal title="Generate Report" onClose={onClose}>
      {templates.length === 0 ? (
        <p className="mb-2 text-xs text-gray-500">No templates available.</p>
      ) : (
        <FormField label="Template" required>
          <select
            value={templateId}
            onChange={(e) => setTemplateId(e.target.value)}
            className="w-full rounded-md border border-gray-700 bg-gray-950 px-2 py-1.5 text-sm text-gray-200"
          >
            {templates.map((t) => (
              <option key={t.template_id} value={t.template_id}>{t.name}</option>
            ))}
          </select>
        </FormField>
      )}
      {error && (
        <p role="alert" className="mt-3 text-xs text-red-400">
          {error}
        </p>
      )}
      <div className="mt-4 flex justify-end gap-2">
        <button onClick={onClose} className="rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300">
          Cancel
        </button>
        <button
          disabled={busy || templates.length === 0}
          onClick={submit}
          className="rounded-md border border-red-800 bg-red-950/50 px-3 py-1.5 text-xs text-red-300 hover:bg-red-900/50 disabled:opacity-50"
        >
          {busy ? "Generating…" : "Generate"}
        </button>
      </div>
    </FormModal>
  );
}

function ScheduleModal({
  templates,
  onClose,
  onCreated,
}: {
  templates: ReportTemplate[];
  onClose: () => void;
  onCreated: () => void;
}) {
  const [templateId, setTemplateId] = useState(templates[0]?.template_id || "");
  const [schedule, setSchedule] = useState("0 * * * *");
  const [cadenceMinutes, setCadenceMinutes] = useState(60);
  const [recipients, setRecipients] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit() {
    if (!templateId) {
      setError("Select a template.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const me = await getMe().catch(() => null);
      await createScheduledReport({
        template_id: templateId,
        schedule,
        cadence_minutes: cadenceMinutes,
        recipients: recipients.split(",").map((r) => r.trim()).filter(Boolean),
        created_by: me?.email || "console",
      });
      onCreated();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to schedule report");
    } finally {
      setBusy(false);
    }
  }

  return (
    <FormModal title="Schedule Report" onClose={onClose}>
      <div className="space-y-3">
        {templates.length === 0 ? (
          <p className="text-xs text-gray-500">No templates available.</p>
        ) : (
          <FormField label="Template" required>
            <select
              value={templateId}
              onChange={(e) => setTemplateId(e.target.value)}
              className="w-full rounded-md border border-gray-700 bg-gray-950 px-2 py-1.5 text-sm text-gray-200"
            >
              {templates.map((t) => (
                <option key={t.template_id} value={t.template_id}>{t.name}</option>
              ))}
            </select>
          </FormField>
        )}
        <FormField label="Cron schedule">
          <input
            value={schedule}
            onChange={(e) => setSchedule(e.target.value)}
            className="w-full rounded-md border border-gray-700 bg-gray-950 px-2 py-1.5 text-sm text-gray-200 font-mono"
          />
        </FormField>
        <FormField label="Cadence (minutes)">
          <input
            type="number"
            value={cadenceMinutes}
            onChange={(e) => setCadenceMinutes(Number(e.target.value))}
            className="w-full rounded-md border border-gray-700 bg-gray-950 px-2 py-1.5 text-sm text-gray-200"
          />
        </FormField>
        <FormField label="Recipients" hint="Comma-separated email addresses.">
          <input
            value={recipients}
            onChange={(e) => setRecipients(e.target.value)}
            placeholder="alice@example.com, bob@example.com"
            className="w-full rounded-md border border-gray-700 bg-gray-950 px-2 py-1.5 text-sm text-gray-200"
          />
        </FormField>
      </div>
      {error && (
        <p role="alert" className="mt-3 text-xs text-red-400">
          {error}
        </p>
      )}
      <div className="mt-4 flex justify-end gap-2">
        <button onClick={onClose} className="rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300">
          Cancel
        </button>
        <button
          disabled={busy || templates.length === 0}
          onClick={submit}
          className="rounded-md border border-red-800 bg-red-950/50 px-3 py-1.5 text-xs text-red-300 hover:bg-red-900/50 disabled:opacity-50"
        >
          {busy ? "Saving…" : "Schedule"}
        </button>
      </div>
    </FormModal>
  );
}
