"""Frozen enums for incident BC (M34)."""

from __future__ import annotations

from enum import StrEnum


class IncidentSeverity(StrEnum):
    P1_CRITICAL = "P1_CRITICAL"
    P2_HIGH = "P2_HIGH"
    P3_MEDIUM = "P3_MEDIUM"
    P4_LOW = "P4_LOW"


class IncidentPhase(StrEnum):
    DECLARED = "DECLARED"
    CLASSIFIED = "CLASSIFIED"
    CONTAINED = "CONTAINED"
    ERADICATED = "ERADICATED"
    RECOVERED = "RECOVERED"
    CLOSED = "CLOSED"


class IncidentTriggerType(StrEnum):
    DETECTION_FINDING = "DETECTION_FINDING"
    INVESTIGATION_ESCALATION = "INVESTIGATION_ESCALATION"
    MANUAL_DECLARATION = "MANUAL_DECLARATION"
    EXTERNAL_NOTIFICATION = "EXTERNAL_NOTIFICATION"


class SeverityClassificationMethod(StrEnum):
    AUTOMATED_FROM_FINDING = "AUTOMATED_FROM_FINDING"
    INVESTIGATION_CONCLUSION = "INVESTIGATION_CONCLUSION"
    MANUAL_DECLARATION = "MANUAL_DECLARATION"
    COMMANDER_OVERRIDE = "COMMANDER_OVERRIDE"


class ResolutionType(StrEnum):
    THREAT_CONTAINED = "threat_contained"
    FALSE_POSITIVE = "false_positive"
    DUPLICATE = "duplicate"
    MERGED = "merged"
    ESCALATED_TO_EXTERNAL = "escalated_to_external"


class ContainmentActionType(StrEnum):
    ALERT_ESCALATION = "ALERT_ESCALATION"
    TRAFFIC_LOGGING = "TRAFFIC_LOGGING"
    PROCESS_TERMINATION = "PROCESS_TERMINATION"
    SERVICE_SUSPENSION = "SERVICE_SUSPENSION"
    CREDENTIAL_REVOKE = "CREDENTIAL_REVOKE"
    ACCOUNT_DISABLE = "ACCOUNT_DISABLE"
    TRAFFIC_BLOCK = "TRAFFIC_BLOCK"
    NETWORK_ISOLATION = "NETWORK_ISOLATION"
    MASS_CREDENTIAL_REVOKE = "MASS_CREDENTIAL_REVOKE"
    MANUAL = "MANUAL"


class ContainmentActionStatus(StrEnum):
    PENDING_AUTH = "PENDING_AUTH"
    AUTHORIZED = "AUTHORIZED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


class ContainmentAuthorizationLevel(StrEnum):
    ANALYST = "ANALYST"
    COMMANDER = "COMMANDER"
    CISO = "CISO"


class EradicationVerificationStatus(StrEnum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    DISPUTED = "DISPUTED"


class RecoveryMilestoneStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"


class TimelineEntryType(StrEnum):
    PHASE_TRANSITION = "PHASE_TRANSITION"
    CONTAINMENT_AUTHORIZED = "CONTAINMENT_AUTHORIZED"
    ERADICATION_SUBMITTED = "ERADICATION_SUBMITTED"
    ERADICATION_VERIFIED = "ERADICATION_VERIFIED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    SEVERITY_RECLASSIFIED = "SEVERITY_RECLASSIFIED"
    INVESTIGATION_LINKED = "INVESTIGATION_LINKED"
    COMMUNICATION_LOGGED = "COMMUNICATION_LOGGED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"


class CommunicationType(StrEnum):
    STAKEHOLDER_UPDATE = "STAKEHOLDER_UPDATE"
    REGULATORY_NOTIFICATION = "REGULATORY_NOTIFICATION"
    INTERNAL = "INTERNAL"
    EXTERNAL_AUTHORITY = "EXTERNAL_AUTHORITY"


class IncidentRole(StrEnum):
    VIEWER = "incident:viewer"
    ANALYST = "incident:analyst"
    COMMANDER = "incident:commander"
    CISO = "incident:ciso"
