"""Frozen enums for integration_hub BC (M35)."""

from __future__ import annotations

from enum import StrEnum


class ConnectorType(StrEnum):
    CLOUD_AWS = "CLOUD_AWS"
    CLOUD_AZURE = "CLOUD_AZURE"
    CLOUD_GCP = "CLOUD_GCP"
    EDR_CROWDSTRIKE = "EDR_CROWDSTRIKE"
    EDR_SENTINELONE = "EDR_SENTINELONE"
    EDR_DEFENDER = "EDR_DEFENDER"
    NETWORK_PALOALTO = "NETWORK_PALOALTO"
    NETWORK_CISCO = "NETWORK_CISCO"
    IDENTITY_OKTA = "IDENTITY_OKTA"
    IDENTITY_AZURE_AD = "IDENTITY_AZURE_AD"
    IDENTITY_PING = "IDENTITY_PING"
    ITSM_SERVICENOW = "ITSM_SERVICENOW"
    ITSM_JIRA = "ITSM_JIRA"
    COMM_SLACK = "COMM_SLACK"
    COMM_TEAMS = "COMM_TEAMS"


class ConnectorStatus(StrEnum):
    REGISTERED = "REGISTERED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    DISABLED = "DISABLED"


class ConnectorHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"


class CircuitState(StrEnum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"


class ConnectorFailureMode(StrEnum):
    TIMEOUT = "TIMEOUT"
    RATE_LIMITED = "RATE_LIMITED"
    AUTH_FAILURE = "AUTH_FAILURE"
    CLIENT_ERROR = "CLIENT_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
